name: tedxcommunity
description: The TEDxCommunity app is an open-source and free-to-use tool designed to help organize a TEDx event.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5 #Public 1.0.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Server
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  #Basic
  provider: ^6.0.5
  intl: ^0.17.0
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  http: ^0.13.5
  file_picker: ^5.2.10
  package_info_plus: ^3.1.0
  flutter_vibrate: ^1.3.0
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  audio_service: ^0.18.9
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  #Design
  cupertino_icons: ^1.0.5
  cupertino_stepper: ^0.2.1
  flutter_cupertino_settings: ^0.5.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_slidable: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_signin_button: ^2.0.0
  macos_ui: ^1.12.2
  siri_wave: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

# Run using flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon.jpg
  web:
    generate: true
    image_path: assets/icon.jpg
    background_color: "#FFFFFF"
    theme_color: "#FF0000."


flutter:

  generate: true
  uses-material-design: true
  assets:
    - assets/